version: '2'

services:

  zookeeper:  
    image: wurstmeister/zookeeper  
    ports:  
      - "2181:2181"
    networks:
      - docker_default_net

  kafka:  
   image: wurstmeister/kafka  
   ports:  
      - "9092:9092"  
   environment:  
     KAFKA_ADVERTISED_HOST_NAME: kafka  
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  
   volumes:  
     - /var/run/docker.sock:/var/run/docker.sock
   networks:
      - docker_default_net

  kafka-mysql-db:
   container_name:  kafka-mysql-db
   image: mysql/mysql-server:5.7
   environment:
     MYSQL_DATABASE: root
     MYSQL_ROOT_PASSWORD: password
     MYSQL_ROOT_HOST: '%'
   ports:
    - "3306:3306"
   volumes:
    - ./mysql-init:/docker-entrypoint-initdb.d/:ro
   restart: always
   networks:
    - docker_default_net

  kafka-consumer-file:
    image:  kafka-consumer-file
    container_name:  kafka-consumer-file
    build:
      context: ./kafka-consumer-file
    ports:
     - 9001:9001
    depends_on:
      - kafka
      - zookeeper
      - kafka-mysql-db
    networks:
      - docker_default_net
 
  kafka-producer-file:
    image:  kafka-producer-file
    container_name:  kafka-producer-file
    build:
      context: ./kafka-producer-file
    volumes:
      - ./data:/data
    ports:
     - 9002:9002
    depends_on:
      - kafka
      - zookeeper
    networks:
    - docker_default_net

networks:
  # docker network create app_private_net --attachable
  docker_default_net:
    external: true
   

    